# Generated by Django 3.2.5 on 2021-08-05 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام محصول')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت محصول')),
                ('includes_taxes', models.BooleanField(verbose_name='آیا مشمول مالیات است ؟')),
                ('catalog_pdf_file', models.FileField(blank=True, null=True, upload_to='pdfs/', verbose_name='پی دی اف کاتالوگ')),
                ('catalog_image_file', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='تصویر کاتالوگ')),
                ('technical_features', models.TextField(verbose_name='ویژگی های فنی')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصول ها',
                'ordering': ('name',),
            },
        ),
    ]
