# Generated by Django 3.2.5 on 2021-08-05 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('last_modified_date', models.DateField(auto_now=True, verbose_name='تاریخ آخرین پیگیری')),
            ],
            options={
                'verbose_name': 'موقعیت',
                'verbose_name_plural': 'موقعیت ها',
                'ordering': ('last_modified_date',),
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='گزارش کار')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='کارشناس فروش')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.opportunity', verbose_name='موقعیت فروش')),
            ],
            options={
                'verbose_name': 'گزارش',
                'verbose_name_plural': 'گزارش ها',
                'ordering': ('create_date',),
            },
        ),
        migrations.CreateModel(
            name='OrganizationProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='محصول مشتری')),
                ('related_products', models.ManyToManyField(to='products.Product', verbose_name='محصولات مرتبط')),
            ],
            options={
                'verbose_name': 'محصول مشتری',
                'verbose_name_plural': 'محصولات مشتری ها',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='نام')),
                ('province', models.CharField(max_length=50, verbose_name='استان')),
                ('phone_number', models.CharField(max_length=20, unique=True, verbose_name='شماره تلفن')),
                ('workers_count', models.IntegerField(verbose_name='تعداد کارگران')),
                ('contact_fullname', models.CharField(max_length=50, verbose_name='نام مخاطب')),
                ('contact_phone_number', models.CharField(max_length=20, verbose_name='شماره تلفن مخاطب')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='ایمیل')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('products', models.ManyToManyField(to='organizations.OrganizationProduct', verbose_name='محصولات')),
                ('registrar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='کارشناس فروش')),
            ],
            options={
                'verbose_name': 'ارگان',
                'verbose_name_plural': 'ارگان ها',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='opportunity',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.organization', verbose_name='ارگان طرف حساب'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='sales_people',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='کارشناسان فروش'),
        ),
    ]
