# Generated by Django 3.2.5 on 2021-08-05 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationproduct',
            options={'ordering': ('name',), 'verbose_name': 'محصول ارگان', 'verbose_name_plural': 'محصولات ارگان'},
        ),
    ]
