# Generated by Django 3.2.5 on 2021-08-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_organizationproduct_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='workers_count',
            field=models.PositiveIntegerField(verbose_name='تعداد کارگران'),
        ),
    ]
