# Generated by Django 3.2.5 on 2021-08-05 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='کارشناس فروش')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.organization', verbose_name='موقعیت فروش')),
            ],
            options={
                'verbose_name': 'پیش فاکتور',
                'verbose_name_plural': 'پیش فاکتور ها',
                'ordering': ('create_date',),
            },
        ),
        migrations.CreateModel(
            name='QouteProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(verbose_name='تعداد')),
                ('price', models.IntegerField(verbose_name='تعداد')),
                ('discount_percent', models.IntegerField(verbose_name='تعداد')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='محصول')),
                ('qoute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='qoutes.qoute', verbose_name='پیش فاکتور')),
            ],
            options={
                'verbose_name': 'جزئیات محصول پیش فاکتور',
                'verbose_name_plural': 'جزئیات محصولات پیش فاکتور',
                'ordering': ('price',),
            },
        ),
    ]
