# Generated by Django 3.2.5 on 2021-08-05 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_organizationproduct_options'),
        ('qoutes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qoute',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.organization', verbose_name='ارگان'),
        ),
    ]
