# Generated by Django 3.2.5 on 2021-08-05 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qoutes', '0002_alter_qoute_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qouteproductdetail',
            name='discount_percent',
            field=models.IntegerField(verbose_name='درصد تخفیف'),
        ),
        migrations.AlterField(
            model_name='qouteproductdetail',
            name='price',
            field=models.IntegerField(verbose_name='قیمت'),
        ),
    ]
