# Generated by Django 3.2.5 on 2021-08-05 10:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0002_alter_organizationproduct_options'),
        ('qoutes', '0003_auto_20210805_0841'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='qoute',
            unique_together={('creator', 'organization')},
        ),
    ]
