# Generated by Django 3.2.5 on 2021-08-05 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qoutes', '0005_auto_20210805_1409'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='qoute',
            unique_together=set(),
        ),
    ]
